### ISSUE TITLE
Can't load static files on homepage

### ISSUE THREAD

**Issue by GuilhermeGZanetti** [jowilf/starlette-admin-demo#56]
I've been trying to launch this demo, but I am failing to do so... I just followed the instructions on the Read.me (cloning and installing dependencies), and tried to run, also as instructed. I don't have any instance of SQL running, so I didn't execute the seed.py. When I run the command 
`$ uvicorn app.main:app`
The server starts running and I can access the localhost:8000, but the static files besides the main homepage html are not loading, as the print below:
![image](https://github.com/jowilf/starlette-admin-demo/assets/51490065/cdf28334-043a-45b8-81af-a049c6352162)

The request for the static files, like the .css is being redirected, not returning anything.
I don't know if I'm doing something wrong, but can you help me with this?

**Comment by GuilhermeGZanetti** [comment]
Thank you! It really worked just by changing starlette's version. You could put that on the requirements.txt, until that's fixed!

**Comment by jowilf** [comment]
I am closing this issue as starlette-admin version 0.13.0 is now compatible with the latest versions of starlette (>= 0.33).
